export const doraResponse = {
  took: 24,
  timed_out: false,
  _shards: { total: 5, successful: 5, failed: 0 },
  hits: {
    total: 2,
    max_score: 47.830826,
    hits: [
      {
        _index: 'people-summary_2018.10.15.17.11.45',
        _type: 'person-summary',
        _id: 'PqwyYMNFST',
        _score: 47.830826,
        _source: {
          phone_numbers: [{ number: null }],
          languages: [],
          legacy_descriptor: {
            legacy_last_updated: '2015-10-28T17:37:57.939-0700',
            legacy_id: 'PqwyYMNFST',
            legacy_ui_id: '1468-5162-5611-5059425',
            legacy_table_name: 'EDPRVCNT',
            legacy_table_description: 'Education Provider Contact',
          },
          last_name: 'Doucette',
          id: 'PqwyYMNFST',
          first_name: 'Kesia',
          sensitivity_indicator: 'N',
          client_counties: [],
        },
        sort: [47.830826, 'person-summary#PqwyYMNFST'],
      },
      {
        _index: 'people-summary_2018.10.15.17.11.45',
        _type: 'person-summary',
        _id: 'NC93eCe0Ra',
        _score: 19.571438,
        _source: {
          csec: [
            {
              description: 'Victim in Open Case not in Foster Care  ',
              csec_code_id: '6870',
              start_date: '2017-08-04',
            },
          ],
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '95522',
              city: 'Gustine',
              county: { description: 'Merced', id: '1091' },
              legacy_descriptor: {
                legacy_last_updated: '2000-08-29T13:24:22.810-0700',
                legacy_id: '07Ukt8C0Ra',
                legacy_ui_id: '0006-8673-9492-0001710',
                legacy_table_name: 'PLC_HM_T',
                legacy_table_description: 'Placement Home',
              },
              street_number: '41234',
              id: '07Ukt8C0Ra',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Resson Street',
            },
            {
              zip: '99999',
              city: 'Merced',
              county: { description: 'Merced', id: '1091' },
              legacy_descriptor: {
                legacy_last_updated: '2018-07-24T15:06:50.945-0700',
                legacy_id: '6gfUBI00Ra',
                legacy_ui_id: '0379-8920-1546-4001710',
                legacy_table_name: 'ADDRS_T',
                legacy_table_description: 'Address',
              },
              street_number: '678',
              id: '6gfUBI00Ra',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: '6th Trail',
            },
          ],
          gender: 'female',
          languages: [],
          date_of_birth: '2000-02-02',
          open_case_responsible_agency_code: 'C',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: 'NC93eCe0Ra',
            legacy_ui_id: '1317-5328-6896-8001710',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Carwardine',
          middle_name: 'Case',
          ssn: '838009854',
          id: 'NC93eCe0Ra',
          first_name: 'Test1A',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Merced', id: '1091' }],
        },
        highlight: {
          autocomplete_search_bar: ['\u003cem\u003eTest1A\u003c/em\u003e'],
        },
        sort: [19.571438, 'person-summary#NC93eCe0Ra'],
      },
    ],
  },
}

export const clientRecord = {
  _index: 'people-summary_2018.10.15.17.11.45',
  _type: 'person-summary',
  _id: 'NC93eCe0Ra',
  _score: 19.571438,
  _source: {
    csec: [
      {
        description: 'Victim in Open Case not in Foster Care  ',
        csec_code_id: '6870',
        start_date: '2017-08-04',
      },
    ],
    race_ethnicity: {
      hispanic_origin_code: 'U',
      unable_to_determine_code: '',
      race_codes: [],
      hispanic_codes: [],
      hispanic_unable_to_determine_code: '',
    },
    addresses: [
      {
        zip: '95522',
        city: 'Gustine',
        county: { description: 'Merced', id: '1091' },
        legacy_descriptor: {
          legacy_last_updated: '2000-08-29T13:24:22.810-0700',
          legacy_id: '07Ukt8C0Ra',
          legacy_ui_id: '0006-8673-9492-0001710',
          legacy_table_name: 'PLC_HM_T',
          legacy_table_description: 'Placement Home',
        },
        street_number: '41234',
        id: '07Ukt8C0Ra',
        type: { description: 'Residence', id: '32' },
        state_code: 'CA',
        street_name: 'Resson Street',
      },
      {
        zip: '99999',
        city: 'Merced',
        county: { description: 'Merced', id: '1091' },
        legacy_descriptor: {
          legacy_last_updated: '2018-07-24T15:06:50.945-0700',
          legacy_id: '6gfUBI00Ra',
          legacy_ui_id: '0379-8920-1546-4001710',
          legacy_table_name: 'ADDRS_T',
          legacy_table_description: 'Address',
        },
        street_number: '678',
        id: '6gfUBI00Ra',
        type: { description: 'Residence', id: '32' },
        state_code: 'CA',
        street_name: '6th Trail',
      },
    ],
    gender: 'female',
    languages: [],
    date_of_birth: '2000-02-02',
    open_case_responsible_agency_code: 'C',
    legacy_descriptor: {
      legacy_last_updated: '2018-07-24T15:08:37.948-0700',
      legacy_id: 'NC93eCe0Ra',
      legacy_ui_id: '1317-5328-6896-8001710',
      legacy_table_name: 'CLIENT_T',
      legacy_table_description: 'Client',
    },
    last_name: 'Carwardine',
    middle_name: 'Case',
    ssn: '838009854',
    id: 'NC93eCe0Ra',
    first_name: 'Test1A',
    sensitivity_indicator: 'N',
    client_counties: [{ description: 'Merced', id: '1091' }],
  },
  highlight: {
    autocomplete_search_bar: ['\u003cem\u003eTest1A\u003c/em\u003e'],
  },
  sort: [19.571438, 'person-summary#NC93eCe0Ra'],
}
