export const searchResponse = {
  took: 31,
  timed_out: false,
  _shards: { total: 5, successful: 5, failed: 0 },
  hits: {
    total: 978,
    max_score: 125.48025,
    hits: [
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: '9GE4pyI0N3',
        _score: 125.48025,
        _source: {
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [],
            hispanic_codes: [{ description: 'Central American', id: '3163' }],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: null,
              city: 'Sacramento',
              county: { description: 'Lake', id: '1084' },
              legacy_descriptor: {
                legacy_last_updated: '2018-04-02T19:24:59.836-0700',
                legacy_id: 'PKU7rHC0N3',
                legacy_ui_id: '1438-7737-0941-4001429',
                legacy_table_name: 'PLC_HM_T',
                legacy_table_description: 'Placement Home',
              },
              id: 'PKU7rHC0N3',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: '2nd street',
            },
            {
              zip: '0',
              city: 'SAC',
              county: { description: 'Lake', id: '1084' },
              legacy_descriptor: {
                legacy_last_updated: '2018-07-24T15:06:50.945-0700',
                legacy_id: 'TQCyu6o0N3',
                legacy_ui_id: '1671-2181-1696-6001429',
                legacy_table_name: 'ADDRS_T',
                legacy_table_description: 'Address',
              },
              id: 'TQCyu6o0N3',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Bluestem Lane',
            },
          ],
          gender: 'female',
          languages: [{ name: 'English', id: '1253', primary: true }],
          date_of_birth: '2000-10-11',
          open_case_responsible_agency_code: 'C',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: '9GE4pyI0N3',
            legacy_ui_id: '0526-0682-6736-6001429',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Fronek',
          id: '9GE4pyI0N3',
          first_name: 'Annie',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Lake', id: '1084' }],
        },
        highlight: { autocomplete_search_bar: ['<em>Annie</em>'] },
        sort: [125.48025, 'person-summary#9GE4pyI0N3'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: 'Qnh1yct0DE',
        _score: 116.67191,
        _source: {
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [{ description: 'White*', id: '839' }],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '95818',
              city: 'Sacramento',
              county: {},
              legacy_descriptor: {
                legacy_last_updated: '2012-05-03T08:28:24.320-0700',
                legacy_id: 'KAck2mB0DE',
                legacy_ui_id: '1145-7385-1453-1000820',
                legacy_table_name: 'PLC_HM_T',
                legacy_table_description: 'Placement Home',
              },
              street_number: '458',
              id: 'KAck2mB0DE',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Zoopey Doopey',
            },
          ],
          gender: 'female',
          languages: [],
          date_of_birth: '1981-01-05',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: 'Qnh1yct0DE',
            legacy_ui_id: '1522-3324-8777-9000820',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Palfery',
          id: 'Qnh1yct0DE',
          first_name: 'Annie',
          sensitivity_indicator: 'N',
          client_counties: [{ id: '0' }],
        },
        highlight: { autocomplete_search_bar: ['<em>Annie</em>'] },
        sort: [116.67191, 'person-summary#Qnh1yct0DE'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: '1xZVT7b0DE',
        _score: 116.67191,
        _source: {
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [{ description: 'White*', id: '839' }],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '64646',
              city: 'Sacramento',
              county: {},
              legacy_descriptor: {
                legacy_last_updated: '2004-05-13T14:04:46.739-0700',
                legacy_id: 'Jxxt93j0DE',
                legacy_ui_id: '1134-1412-5987-5000820',
                legacy_table_name: 'PLC_HM_T',
                legacy_table_description: 'Placement Home',
              },
              street_number: '9789',
              id: 'Jxxt93j0DE',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Oompah Way',
            },
          ],
          gender: 'female',
          languages: [],
          date_of_birth: '1980-01-04',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: '1xZVT7b0DE',
            legacy_ui_id: '0111-3767-4454-7000820',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Willder',
          id: '1xZVT7b0DE',
          first_name: 'Annie',
          sensitivity_indicator: 'N',
          client_counties: [{ id: '0' }],
        },
        highlight: { autocomplete_search_bar: ['<em>Annie</em>'] },
        sort: [116.67191, 'person-summary#1xZVT7b0DE'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: 'U2l2Uuy0Bv',
        _score: 116.26213,
        _source: {
          phone_numbers: [{ number: '7310002410', type: 'Home' }],
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [{ description: 'White*', id: '839' }, { description: 'American Indian*', id: '821' }],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '95971',
              phone_numbers: [{ number: '7310002410', type: 'Home' }],
              city: 'Quincy',
              county: { description: 'Plumas', id: '1099' },
              legacy_descriptor: {
                legacy_last_updated: '2018-07-24T15:06:50.945-0700',
                legacy_id: 'H9FVE8a0Bv',
                legacy_ui_id: '0974-0782-8797-2000739',
                legacy_table_name: 'ADDRS_T',
                legacy_table_description: 'Address',
              },
              street_number: '62',
              effective_start_date: '1999-12-08',
              id: 'H9FVE8a0Bv',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Cordelia Plaza',
            },
          ],
          gender: 'female',
          languages: [{ name: 'English', id: '1253', primary: true }],
          date_of_birth: '1987-07-09',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: 'U2l2Uuy0Bv',
            legacy_ui_id: '1706-5344-1648-4000739',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Catley',
          id: 'U2l2Uuy0Bv',
          first_name: 'Annie',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Imperial', id: '1080' }, { description: 'Plumas', id: '1099' }],
        },
        highlight: { autocomplete_search_bar: ['<em>Annie</em>'] },
        sort: [116.26213, 'person-summary#U2l2Uuy0Bv'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: 'H3lQylH0Fz',
        _score: 116.26213,
        _source: {
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [{ description: 'White*', id: '839' }],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '93512',
              phone_numbers: [{ number: '6199332204', type: 'Home' }],
              city: 'BENTON',
              county: {},
              legacy_descriptor: {
                legacy_last_updated: '2000-01-18T12:51:20.148-0800',
                legacy_id: 'Isb0HbP0Fz',
                legacy_ui_id: '1072-4222-0553-9000991',
                legacy_table_name: 'PLC_HM_T',
                legacy_table_description: 'Placement Home',
              },
              id: 'Isb0HbP0Fz',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'N. HIGHWAY 6',
            },
          ],
          gender: 'female',
          languages: [{ name: 'English', id: '1253', primary: true }],
          date_of_birth: '1981-09-03',
          open_case_responsible_agency_code: 'C',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: 'H3lQylH0Fz',
            legacy_ui_id: '0969-0533-2131-5000991',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Trehearn',
          phone_numbers: [{ number: '6199332204', type: 'Home' }],
          id: 'H3lQylH0Fz',
          first_name: 'Annie',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Mono', id: '1093' }],
        },
        highlight: { autocomplete_search_bar: ['<em>Annie</em>'] },
        sort: [116.26213, 'person-summary#H3lQylH0Fz'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: 'JqGPr4a0Um',
        _score: 23.390545,
        _source: {
          phone_numbers: [{ number: '8090004222', type: 'Home' }],
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [{ description: 'White*', id: '839' }],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: null,
              city: 'Sacramento',
              county: { description: 'Mendocino', id: '1090' },
              legacy_descriptor: {
                legacy_last_updated: '2004-09-27T08:07:17.848-0700',
                legacy_id: 'GoCJw2S0Um',
                legacy_ui_id: '0954-7924-7831-2001908',
                legacy_table_name: 'PLC_HM_T',
                legacy_table_description: 'Placement Home',
              },
              street_number: '1301',
              id: 'GoCJw2S0Um',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: '62nd Street',
            },
            {
              zip: '95944',
              phone_numbers: [{ number: '8090004222', type: 'Home' }],
              city: 'Mendocino',
              county: { description: 'Mendocino', id: '1090' },
              legacy_descriptor: {
                legacy_last_updated: '2018-07-24T15:06:50.945-0700',
                legacy_id: '6quAPBg0Um',
                legacy_ui_id: '0389-2702-7568-8001908',
                legacy_table_name: 'ADDRS_T',
                legacy_table_description: 'Address',
              },
              street_number: '123',
              effective_start_date: '2004-07-16',
              id: '6quAPBg0Um',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Haas Plaza',
            },
          ],
          gender: 'female',
          languages: [{ name: 'English', id: '1253', primary: true }],
          date_of_birth: '1992-09-01',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: 'JqGPr4a0Um',
            legacy_ui_id: '1127-0859-6695-2001908',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Jain',
          id: 'JqGPr4a0Um',
          first_name: 'Steve',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Mendocino', id: '1090' }],
        },
        sort: [23.390545, 'person-summary#JqGPr4a0Um'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: 'SdscHeU0EE',
        _score: 22.515915,
        _source: {
          phone_numbers: [{ number: '9660003841', type: 'Home' }],
          race_ethnicity: {
            hispanic_origin_code: 'Y',
            unable_to_determine_code: '',
            race_codes: [],
            hispanic_codes: [{ description: 'Mexican', id: '3164' }],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '99089',
              phone_numbers: [{ number: '9660003841', type: 'Home' }],
              city: 'Yuba City',
              county: { description: 'Sutter', id: '1118' },
              legacy_descriptor: {
                legacy_last_updated: '2018-07-24T15:06:50.945-0700',
                legacy_id: 'B9Q7qAU0EE',
                legacy_ui_id: '0633-4338-4048-2000882',
                legacy_table_name: 'ADDRS_T',
                legacy_table_description: 'Address',
              },
              street_number: '2211',
              effective_start_date: '1998-12-21',
              id: 'B9Q7qAU0EE',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Schurz Plaza',
            },
          ],
          gender: 'female',
          languages: [{ name: 'Spanish', id: '1274', primary: true }, { name: 'English', id: '1253', primary: false }],
          date_of_birth: '1965-03-27',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: 'SdscHeU0EE',
            legacy_ui_id: '1626-9428-2326-6000882',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Jenno',
          id: 'SdscHeU0EE',
          first_name: 'Tina',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Sutter', id: '1118' }],
        },
        sort: [22.515915, 'person-summary#SdscHeU0EE'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: 'NTy91S00Lc',
        _score: 20.946577,
        _source: {
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '0',
              phone_numbers: [{ number: '8480007192', type: 'Home' }],
              city: 'seaside',
              county: { description: 'Monterey', id: '1094' },
              legacy_descriptor: {
                legacy_last_updated: '2018-07-24T15:06:50.945-0700',
                legacy_id: '3Q9J2OK0Lc',
                legacy_ui_id: '0194-3576-8483-6001340',
                legacy_table_name: 'ADDRS_T',
                legacy_table_description: 'Address',
              },
              id: '3Q9J2OK0Lc',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Holmberg Circle',
            },
          ],
          gender: 'male',
          languages: [],
          date_of_birth: '1988-11-14',
          open_case_responsible_agency_code: 'C',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: 'NTy91S00Lc',
            legacy_ui_id: '1333-8620-0125-2001340',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Mendel',
          phone_numbers: [{ number: '8480007192', type: 'Home' }],
          id: 'NTy91S00Lc',
          first_name: 'Ann',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Monterey', id: '1094' }],
        },
        highlight: { autocomplete_search_bar: ['<em>Ann</em>'] },
        sort: [20.946577, 'person-summary#NTy91S00Lc'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: 'IMwzk980MV',
        _score: 20.466972,
        _source: {
          phone_numbers: [{ number: '9620005475', type: 'Home' }, { number: '9164549676', type: 'Home' }],
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [{ description: 'White*', id: '839' }],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '95818',
              phone_numbers: [{ number: '9164549676', type: 'Home' }],
              city: 'SACRAMENTO',
              county: {},
              legacy_descriptor: {
                legacy_last_updated: '1998-04-30T13:02:47.109-0700',
                legacy_id: 'EkG4IQo0MV',
                legacy_ui_id: '0837-5828-5399-0001395',
                legacy_table_name: 'PLC_HM_T',
                legacy_table_description: 'Placement Home',
              },
              street_number: '2900',
              id: 'EkG4IQo0MV',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: '24TH STREET',
            },
            {
              zip: '95368',
              phone_numbers: [{ number: '9620005475', type: 'Home' }],
              city: 'Salida',
              county: { description: 'State of California', id: '1126' },
              legacy_descriptor: {
                legacy_last_updated: '2018-07-24T15:06:50.945-0700',
                legacy_id: 'JhGNrj40MV',
                legacy_ui_id: '1118-8402-9731-8001395',
                legacy_table_name: 'ADDRS_T',
                legacy_table_description: 'Address',
              },
              street_number: '9999',
              effective_start_date: '2002-08-01',
              id: 'JhGNrj40MV',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Merchant Way',
            },
          ],
          gender: 'female',
          languages: [{ name: 'English', id: '1253', primary: true }],
          date_of_birth: '1990-12-14',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: 'IMwzk980MV',
            legacy_ui_id: '1043-4309-0570-2001395',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Morgen',
          id: 'IMwzk980MV',
          first_name: 'Anna',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Stanislaus', id: '1117' }],
        },
        highlight: { autocomplete_search_bar: ['<em>Anna</em>'] },
        sort: [20.466972, 'person-summary#IMwzk980MV'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
      {
        _index: 'people-summary_2018.11.06.16.20.00',
        _type: 'person-summary',
        _id: '2p3Fiek0OV',
        _score: 20.466972,
        _source: {
          phone_numbers: [{ number: '9480004736', type: 'Home' }],
          race_ethnicity: {
            hispanic_origin_code: 'U',
            unable_to_determine_code: '',
            race_codes: [],
            hispanic_codes: [],
            hispanic_unable_to_determine_code: '',
          },
          addresses: [
            {
              zip: '92020',
              phone_numbers: [{ number: '9480004736', type: 'Home' }],
              city: 'Sacramento',
              county: { description: 'Sacramento', id: '1101' },
              legacy_descriptor: {
                legacy_last_updated: '2018-07-24T15:06:50.945-0700',
                legacy_id: 'K56k6vm0OV',
                legacy_ui_id: '1140-6850-2359-0001519',
                legacy_table_name: 'ADDRS_T',
                legacy_table_description: 'Address',
              },
              street_number: '6652',
              effective_start_date: '1999-12-04',
              id: 'K56k6vm0OV',
              type: { description: 'Residence', id: '32' },
              state_code: 'CA',
              street_name: 'Glendale Street',
            },
          ],
          gender: 'female',
          languages: [],
          date_of_birth: '1998-10-13',
          legacy_descriptor: {
            legacy_last_updated: '2018-07-24T15:08:37.948-0700',
            legacy_id: '2p3Fiek0OV',
            legacy_ui_id: '0160-3713-2119-0001519',
            legacy_table_name: 'CLIENT_T',
            legacy_table_description: 'Client',
          },
          last_name: 'Livings',
          id: '2p3Fiek0OV',
          first_name: 'Anna',
          sensitivity_indicator: 'N',
          client_counties: [{ description: 'Sacramento', id: '1101' }],
        },
        highlight: { autocomplete_search_bar: ['<em>Anna</em>'] },
        sort: [20.466972, 'person-summary#2p3Fiek0OV'],
        inner_hits: {
          addresses: { hits: { total: 0, max_score: null, hits: [] } },
        },
      },
    ],
  },
}
